#!/usr/bin/env bash
set -euo pipefail

# Verify that a release asset directory exactly matches .github/release-assets.txt:
#   1. The directory's regular-file list must exactly equal the manifest;
#   2. SHA256SUMS must cover every manifest asset other than itself exactly once;
#   3. Every checksum must verify.
# The manifest is the single source of truth for release assets; adding or renaming an asset requires changing only it.
#
# Usage:
#   release-verify-assets.sh <directory>
#   release-verify-assets.sh <directory> <trusted-checksum-file>
#
# Verifying assets downloaded remotely requires the second argument. The directory's SHA256SUMS is then untrusted input, used only for identity comparison and never executed; verification always uses the trusted copy generated by the current run.

directory="${1:?release asset directory is required}"
trusted_checksums="${2:-}"
manifest="${RELEASE_ASSET_MANIFEST:-.github/release-assets.txt}"

absolute_path() {
  printf '%s/%s' "$(cd "$(dirname "$1")" && pwd)" "$(basename "$1")"
}

test -d "${directory}"
test -s "${manifest}"
manifest="$(absolute_path "${manifest}")"
if [[ -n "${trusted_checksums}" ]]; then
  test -s "${trusted_checksums}"
  trusted_checksums="$(absolute_path "${trusted_checksums}")"
fi

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

# The manifest itself must remain C-locale sorted, otherwise later cmp calls can vary with the locale.
LC_ALL=C sort "${manifest}" >"${work}/expected"
cmp "${manifest}" "${work}/expected"

find "${directory}" -mindepth 1 -maxdepth 1 -type f -exec basename {} \; |
  LC_ALL=C sort >"${work}/actual"
cmp "${work}/expected" "${work}/actual"

grep -vFx 'SHA256SUMS' "${work}/expected" >"${work}/expected-checksummed"

cd "${directory}"
awk '{print $2}' SHA256SUMS | LC_ALL=C sort >"${work}/actual-checksummed"
cmp "${work}/expected-checksummed" "${work}/actual-checksummed"

# release-assets-trusted-checksum:start
if [[ -n "${trusted_checksums}" ]]; then
  cmp "${trusted_checksums}" SHA256SUMS
  sha256sum --check "${trusted_checksums}"
else
  sha256sum --check SHA256SUMS
fi
# release-assets-trusted-checksum:end
